name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  chewie_audio: ^1.5.0
  flutter:
    sdk: flutter
  just_audio: ^0.9.37

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/musics/1.mp3
    - assets/musics/2.mp3
    - assets/musics/3.mp3
    - assets/musics/4.mp3
    - assets/musics/5.mp3
    - assets/musics/6.mp3

    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
